modLoader="javafml"
loaderVersion="${loader_range}"
issueTrackerURL="https://github.com/KnightMiner/Metalborn/issues/"
license="MIT"
[[mods]]
modId="metalborn"
version="${version}"
displayName="Metalborn"
displayURL="https://github.com/KnightMiner/Metalborn"
# logoFile="examplemod.png"
credits="Brandon Sanderson, writer of Mistborn, created the magic that inspired this mod."
authors="KnightMiner"
description='''
Metalborn adds in Feruchemy, which allows storing attributes in metal, making you temporarily weaker. Those attributes can later be tapped to boost your power.
'''
[[dependencies.metalborn]] 
    modId="forge"
    mandatory=true
    versionRange="${forge_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies.metalborn]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.metalborn]]
    modId="mantle"
    mandatory=true
    versionRange="${mantle_range}"
    ordering="NONE"
    side="BOTH"
